name: Native Image
on:
  push:
    branches:
      - master
      - main
  pull_request:
  release:
    types: [published]
jobs:
  unix:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            uploaded_filename: decline-app-test-x86_64-pc-linux
            local_path: decline-app-test/target/native-image/decline-app-test
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v13
      - run: git fetch --tags || true
      - run: sbt nativeImageCommand
        shell: bash
      - run: sbt nativeImageRunAgent
        shell: bash
      - run: sbt nativeImage
        shell: bash
      - run: echo $(pwd)
        shell: bash
      - uses: actions/upload-artifact@v2
        with:
          path: ${{ matrix.local_path }}
          name: ${{ matrix.uploaded_filename }}
      - name: Upload release
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ matrix.local_path }}
          asset_name: ${{ matrix.uploaded_filename }}
          asset_content_type: application/zip
