name: Native Image
on:
  push:
    branches:
      - master
      - main
  pull_request:
  release:
    types: [published]
jobs:
  unix:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
        include:
          - os: macOS-latest
            uploaded_filename: decline-app-test-x86_64-apple-darwin
            local_path: decline-app-test/target/native-image/decline-app-test
          - os: ubuntu-latest
            uploaded_filename: decline-app-test-x86_64-pc-linux
            local_path: decline-app-test/target/native-image/decline-app-test
          - os: windows-latest
            uploaded_filename: decline-app-test-x86_64-pc-win32.exe
            local_path: decline-app-test\target\native-image\decline-app-test.exe
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v13
      - run: git fetch --tags || true
      - run: sbt root/nativeImageRunAgent
        shell: bash
        if: ${{ matrix.os != 'windows-latest' }}
      - run: sbt root/nativeImage
        shell: bash
        if: ${{ matrix.os != 'windows-latest' }}
      - run: echo $(pwd)
        shell: bash
      - name: sbt test
        shell: cmd
        if: ${{ matrix.os == 'windows-latest' }}
        run: >-
          "C:\Program Files (x86)\Microsoft Visual
          Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat" && sbt
          root/nativeImage
      - uses: actions/upload-artifact@v2
        with:
          path: ${{ matrix.local_path }}
          name: ${{ matrix.uploaded_filename }}
      - name: Upload release
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ matrix.local_path }}
          asset_name: ${{ matrix.uploaded_filename }}
          asset_content_type: application/zip
